[package]
name = "helping-hand"
version = "0.1.0"
publish = false
authors = ["Jesse Fischbeck <jlevifisch@gmail.com>"]
edition = "2021"

[dependencies]
bevy = { version = "^0.12", features = ["file_watcher"] }
bevy_ecs_ldtk = "^0.9"
bevy_kira_audio = { version = "^0.18", features = ["wav"] }
unicode-segmentation = "^1.10"

[dev-dependencies]
cucumber = "^0.21"
futures = "0.3"

# When adding a new feature, add a new Cucumber Test below
# following the format below:
[[test]]
name = "menus"
harness = false