[package]
name = "helping-hand"
version = "0.1.0"
publish = false
authors = ["Jesse Fischbeck <jlevifisch@gmail.com>"]
edition = "2021"

[dependencies]
bevy = "^0.11"
bevy_ecs_ldtk = "^0.8"
bevy_kira_audio = { version = "^0.16", features = ["wav"] }
unicode-segmentation = "^1.10"

[dev-dependencies]
cucumber = "0.20"
futures = "0.3"

# When adding a new feature, add a new Cucumber Test below
# following the format below:
[[test]]
name = "menus"
harness = false