[package]
name = "helping-hand"
version = "0.1.0"
publish = false
authors = ["Jesse Fischbeck <jlevifisch@gmail.com>"]
edition = "2021"

[dependencies]
bevy = "^0.7"
bevy_ecs_ldtk = "^0.3"
bevy_kira_audio = "^0.10"

[features]
default = [
    "bevy/bevy_winit",
    "bevy/render",
    "bevy/png",
    "bevy/x11",
    "bevy_kira_audio/wav"
]

dev = [
    "bevy/dynamic",
]