[package]
name = "helping-hand"
version = "0.1.0"
authors = ["Jesse Fischbeck <jlevifisch@gmail.com>"]
edition = "2021"

[dependencies]
bevy = "^0.6"
bevy_ecs_tilemap = "^0.5"
anyhow = "^1.0"
tiled = "^0.9"
log = "^0.4"