[package]
name = "helping-hand"
version = "0.1.0"
publish = false
authors = ["Jesse Fischbeck <jlevifisch@gmail.com>"]
edition = "2021"

[dependencies]
bevy = "^0.7"
bevy_ecs_ldtk = "^0.3"
bevy_kira_audio = { version = "^0.10", features = ["wav"] }