[package]
name = "helping-hand"
version = "0.1.0"
publish = false
authors = ["Jesse Fischbeck <jlevifisch@gmail.com>"]
edition = "2021"

[dependencies]
bevy = "^0.11"
bevy_ecs_ldtk = "^0.8"
bevy_kira_audio = { version = "^0.16", features = ["wav"] }
unicode-segmentation = "^1.10"

# One layer of the LDTK map will not render without this patch from bevy_ecs_tilemap, which bevy_ecs_ldtk
# uses as dependency. Remove this once bevy_ecs_tilemap has a new update, since it should hopefully be fixed
# by then.
[patch.crates-io]
bevy_ecs_tilemap = { git = "http://github.com/StarArawn/bevy_ecs_tilemap", version = "0.11", branch = "main" }