on:
  push:
    branches: [ main ]

name: Auto-Formatter

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: Install Audio Driver via Alsa for Linux
        run: sudo apt update && sudo apt-get install libasound2-dev libudev-dev mold
        shell: bash
      - uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
